server:
  port: 8077

logging:
  level:
    com.insectSituation.controller: INFO

spring:
  servlet:
    multipart:
      #不限制文件上传的大小，设置为-1
      #单个文件的大小
      max-file-size: 256MB
      #单次请求的文件的总大小
      max-request-size: 1024MB
  redis:
    # 地址
    host: 36.138.168.13
    # 端口，默认为6379
    port: 56379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: zD%8fwgOgEhuHgKm
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false
  datasource:
    name: jetlinks
    username: root
    password: 3+PloXbwcM7+JA=
    url: jdbc:mysql://101.201.119.26:30016/jetlinks?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  #是否开启Knife4j增强模式
  enable: true
  #设置密码
  basic:
    enable: true
    username: test
    password: 12313

analyzer:
  #通讯端口 (int类型)
  deviceConnectPort: 8045
  #图片上传位置
  imageFilePath: D:\mnt\webJava\resources\static\
  #推送地址
  notifyUrlBase: http://localhost:8077
  #图片上传推送
  imageUploadNotifyUrl: /sdk/fileAddress
  #登录帧
  deviceLoginNotifyUrl: /sdk/login
  #实时数据帧
  deviceRealTimeDataNotifyUrl : /sdk/realTimeData
  #控制指令应答帧
  deviceCtrlResultNotifyUrl: /sdk/ctrl
  #设备参数应答帧
  deviceReceiveDataNotifyUrl: /sdk/receive
  #数据透传应答帧
  deviceTransDataNotifyUrl: /sdk/trans